import type { Group } from "../types";

export const DEMO_ID = "u_demo";
export const DEMO_EMAIL = "demo@studysync.app";

const HOUR = 3_600_000;
const DAY = 86_400_000;

export const SEED_GROUPS: Group[] = [
  {
    id: "g1",
    subject: "Linear Algebra",
    level: "Intermediate",
    description:
      "Working through Strang's textbook — eigenvalues, SVD, and applications. Weekly problem sets.",
    timing: "Tue & Thu, 7–9 PM",
    timeSlot: "Evening",
    mode: "Online",
    ownerId: DEMO_ID,
    ownerName: "Aisha Patel",
    members: [
      { id: DEMO_ID, name: "Aisha Patel", role: "admin" },
      { id: "u2", name: "Marco Liu", role: "member" },
      { id: "u3", name: "Sara Kim", role: "member" },
    ],
    messages: [
      {
        id: "m1",
        userId: "u2",
        userName: "Marco Liu",
        text: "Anyone got notes on chapter 6?",
        timestamp: Date.now() - HOUR,
        reactions: { "\u{1F44D}": ["u3"] },
        readBy: ["u2", "u3"],
      },
      {
        id: "m2",
        userId: DEMO_ID,
        userName: "Aisha Patel",
        text: "I'll share mine tonight!",
        timestamp: Date.now() - HOUR / 2,
        readBy: [DEMO_ID, "u2", "u3"],
      },
    ],
    sessions: [
      {
        id: "s1",
        title: "SVD review session",
        startsAt: Date.now() + DAY * 2,
        durationMin: 90,
        createdBy: DEMO_ID,
      },
    ],
    quizzes: [],
    quizAttempts: [],
    joinRequests: [],
    createdAt: Date.now() - DAY * 4,
  },
  {
    id: "g2",
    subject: "Operating Systems",
    level: "Advanced",
    description:
      "Deep dive into xv6, scheduling, and concurrency. Pair programming on labs.",
    timing: "Sat, 10 AM–1 PM",
    timeSlot: "Weekend",
    mode: "Offline",
    ownerId: "u4",
    ownerName: "Daniel Okafor",
    members: [
      { id: "u4", name: "Daniel Okafor", role: "admin" },
      { id: "u5", name: "Priya Singh", role: "member" },
    ],
    messages: [],
    sessions: [],
    quizzes: [],
    quizAttempts: [],
    joinRequests: [],
    requireApproval: true,
    createdAt: Date.now() - DAY * 2,
  },
  {
    id: "g3",
    subject: "React & TypeScript",
    level: "Beginner",
    description:
      "Build small projects together — todo apps, dashboards, and mini portfolios. Friendly to newcomers!",
    timing: "Mon & Wed, 6–7:30 PM",
    timeSlot: "Evening",
    mode: "Online",
    ownerId: "u6",
    ownerName: "Lena Hofer",
    members: [{ id: "u6", name: "Lena Hofer", role: "admin" }],
    messages: [],
    sessions: [],
    quizzes: [],
    quizAttempts: [],
    joinRequests: [],
    createdAt: Date.now() - DAY,
  },
  {
    id: "g4",
    subject: "Organic Chemistry",
    level: "Intermediate",
    description:
      "Reaction mechanisms, synthesis problems, exam prep. We meet at the campus library.",
    timing: "Fri, 4–6 PM",
    timeSlot: "Afternoon",
    mode: "Offline",
    ownerId: "u7",
    ownerName: "Jamal Rivera",
    members: [
      { id: "u7", name: "Jamal Rivera", role: "admin" },
      { id: "u8", name: "Mei Zhang", role: "member" },
      { id: "u9", name: "Tom Becker", role: "member" },
      { id: "u10", name: "Nora Ali", role: "member" },
    ],
    messages: [],
    sessions: [],
    quizzes: [],
    quizAttempts: [],
    joinRequests: [],
    createdAt: Date.now() - DAY * 6,
  },
  {
    id: "g5",
    subject: "Machine Learning",
    level: "Advanced",
    description:
      "Reading group on transformers, diffusion, and recent ICML papers. Bring your own questions.",
    timing: "Sun, 3–5 PM",
    timeSlot: "Weekend",
    mode: "Online",
    ownerId: "u11",
    ownerName: "Ravi Kumar",
    members: [
      { id: "u11", name: "Ravi Kumar", role: "admin" },
      { id: "u12", name: "Elena Costa", role: "member" },
    ],
    messages: [],
    sessions: [],
    quizzes: [],
    quizAttempts: [],
    joinRequests: [],
    createdAt: Date.now() - DAY * 3,
  },
  {
    id: "g6",
    subject: "Calculus II",
    level: "Beginner",
    description: "Integration techniques, series, and exam grinding. Snacks welcome.",
    timing: "Wed, 5–7 PM",
    timeSlot: "Evening",
    mode: "Offline",
    ownerId: "u13",
    ownerName: "Hana Sato",
    members: [{ id: "u13", name: "Hana Sato", role: "admin" }],
    messages: [],
    sessions: [],
    quizzes: [],
    quizAttempts: [],
    joinRequests: [],
    createdAt: Date.now() - DAY * 5,
  },
];
